### PR TITLE
Replacing AIA photo with better cropping & resolution

### PR DESCRIPTION
**Pull request by gnadt**
Updated the AIA photo, not sure why the images don't have extensions though?

### CODE REVIEW

**Comment by emmanuellujan** [comment]
This new version of the image has a wider sky. Please see if you like how it looks when a circle is cropped out of the image (https://julia.mit.edu/research-grants/).

**Comment by emmanuellujan** [comment]
As for the extension, the internal project name (in this case AIA) is used as the image name, which saves a column in [this table](https://github.com/JuliaLabs/julialabs.github.io/blob/master/_assets/research-grants.csv).

**Comment by gnadt** [comment]
Yeah I like that better, though a blue background would be even better, I might do that. Oh I meant why don't the images use .png, etc.? (but maybe this is a web dev thing I don't know about)

**Comment by emmanuellujan** [comment]
An alternative to loading images with their extension is to use the internal project name (from the table I mentioned) and look in the image directory for the image that has that name, regardless of its extension, and then load that image. Currently it simply takes the internal project name from the table and uses that name to load the image.

**Pull request merged**
